services:
  aples:
    container_name: aples_container
    build:
      context: ./docker
    volumes:
      - ./src:/aples
      - ./data:/aples/data
    command: tail -f /dev/null
    restart: on-failure